version: '3.9'

x-user-credentials: &database-authentication
  POSTGRES_USER: librarian
  POSTGRES_PASSWORD: j^8d94asTq#v
  POSTGRES_DB: book-store

services:

  book-manager:
    image: tensorflow/book-manager:v0.0.1
    container_name: book-manager-app
    build:
      dockerfile: ./Dockerfile.app
    environment: *database-authentication
    networks:
      - book-network
    volumes:
      - ./app:/app
    depends_on:
      - postgre-database
    command: python3 main.py

  postgre-database:
    image: postgres/book-manager:v0.0.1
    container_name: postgre-db
    build:
      dockerfile: ./Dockerfile.database
    restart: unless-stopped
    shm_size: 128mb
    environment: *database-authentication
    ports:
      - 15432:5432
    volumes:
      - ./postgre-data:/var/lib/postgresql/data
    networks:
      - book-network

networks:
  book-network:
    name: book-network
    driver: bridge
    external: false