version: '3.9'

services:

  book-manager:
    image: tensorflow/book-manager:v0.0.1
    container_name: book-manager-app
    build:
      dockerfile: ./Dockerfile.app
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - book-network
    volumes:
      - ./app:/app
    volumes_from:
      - postgre-database
    depends_on: 
      - postgre-database
    healthcheck:
      test: nvidia-smi
      interval: 5s
      timeout: 5s
      retries: 3
    command: sleep infinity

  postgre-database:
    image: postgres/book-manager:v0.0.1
    container_name: postgre-db
    build:
      dockerfile: ./Dockerfile.database
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: librarian
      POSTGRES_PASSWORD: j^8d94asTq#v
      POSTGRES_DB: book-store
    volumes:
      - ./postgre-data:/var/lib/postgresql/data
      - book-volume:/var/run
    networks:
      - book-network
  database-adminer:
    image: adminer
    container_name: db-adminer
    restart: unless-stopped
    ports:
      - 18080:8080
    networks:
      - book-network

volumes:
  book-volume:
    name: book-volume
    external: false

networks:
  book-network:
    name: book-network
    driver: bridge
    external: false