version: '3.9'

x-user-credentials: &database-authentication
  POSTGRES_USER: librarian
  POSTGRES_PASSWORD: j^8d94asTq#v
  POSTGRES_DB: book-store

services:

  book-manager-init:
    image: tensorflow/book-manager:v0.0.1
    container_name: book-manager-init
    build:
      dockerfile: ./Dockerfile.init
    environment:
      <<: *database-authentication
      POSTGRES_SERVICE: postgres-database
    networks:
      - book-network
    depends_on:
      - postgres-database
    volumes:
      - ./app:/app
    command: ["python3", "-m", "settings.run"]

  book-manager:
    image: tensorflow/book-manager:v0.0.1
    container_name: book-manager-app
    environment:
      <<: *database-authentication
      POSTGRES_SERVICE: postgres-database
    networks:
      - book-network
    volumes_from:
      - book-manager-init
    depends_on:
      - book-manager-init
    ports:
      - 15000:5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: nvidia-smi
      interval: 5s
      timeout: 5s
      retries: 3
    command: ["python3", "-m", "streamlit", "run", "main.py", "--server.port", "5000"]

  postgres-database:
    image: postgres/book-manager:v0.0.1
    container_name: postgres-db
    build:
      dockerfile: ./Dockerfile.database
    restart: unless-stopped
    shm_size: 128mb
    environment: *database-authentication
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - book-network

  adminer:
    image: adminer
    container_name: db-adminer
    restart: always
    ports:
      - 18080:8080
    networks:
      - book-network

networks:
  book-network:
    name: book-network
    driver: bridge
    external: false
